# Generated by Django 2.0.2 on 2018-02-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataHelper', '0002_auto_20180212_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
